### ISSUE TITLE
Is the second culture poster supposed to read "No, we can't. How might we"

### ISSUE THREAD

**Issue by shiraleeana** [govau/service-manual#713]
Not "**Not**, we can't. How might we?"?
https://guides.service.gov.au/assets/files/design-principles/dta-culture-posters.pdf

**Comment by sirleech** [comment]
Thanks for this issue report Shira. I'm unsure of the original copy of this poster, can you give me more background?

**Comment by shiraleeana** [comment]
Hi Christopher,
I'm not sure – just thought to flag it.

**Comment by mibraheim** [comment]
Hi @shiraleeana - it should read '**_Not_**, we can't. How might we?'.  The intent is that rather than saying something isn't possible, we begin to ideate about what might be.   

Sometimes teams get stuck with a problem and it appears that there isn't a way to solve it. Rather than just giving up, we want to encourage them to look at things from a different point of view - to consider other alternatives.

**Comment by shiraleeana** [comment]
Hi Mariam! Ah, I'm just being pedantic about grammar then. All good. Feel like it should be `Not: "we can't". "How might we?"`
